### PR TITLE
Use streams for bridge methods that return string output

### PR DESCRIPTION
**Pull request by sylvestor88**
Made few other changes based on Ariels feedback. Changed the two bridge methods to return InputStream instead of String. You can ignore the changes made for ctool as that was mainly done to avoid errors. I might be changing those based on ctool implementation.

### CODE REVIEW

**Comment by ptnapoleon** [comment]
I don't think there is any need to use a Stream for readClusterLogs, since that is currently purely for post-processing, and just makes the code a lot clunkier. -1 there.

**Comment by ptnapoleon** [comment]
Ariel was more asking for InputStreams as returns from calls to nodetool, or other tools where we're blocking for the output to complete, and then returning the whole output as a String

**Comment by sylvestor88** [comment]
I agree with making it clunkier.. But I thought the changes were to be made for abstract bridge methods, so changed the two.. Will discard the previous changes and make new

**Comment by sylvestor88** [comment]
Most changes are relevant to CCMBridge. CtoolBridge has been changed a lot since the last push. Will be creating a PR for that tomorrow

**Comment by ptnapoleon** [comment]
Is this ready for merging? It looks fine.

**Comment by sylvestor88** [comment]
Yeah, This can be merged. Will be creating another PR for ctool

**Pull request merged**
