### PR TITLE
Ctool Support for the harness

### PR DESCRIPTION
**Pull request by sylvestor88**
Ctool Support for the harness

### CODE REVIEW

**Comment by ptnapoleon** [comment]
Looks good, except for one thing. We shouldn't be hardcoding a branch of C\* to be installed on ctool. Instead, we should be installing the current repository we're running out of. You will probably need to scp the code, rather than using the `ctool install` feature.

**Comment by sylvestor88** [comment]
Hey Philip, didn't know you were gonna check this before next week. Was gonna ping Ryan for it. I will look into the C\* installation part. Also, the stress tests are throwing exception for ctool which I think has something to do with the modules. I am planning to look into it once I am done with providing support for all tools.

**Comment by ptnapoleon** [comment]
Sounds good to me

**Comment by sylvestor88** [comment]
Hey Philip, I able to scp the working repo to all the nodes of the cluster but getting errors on getting those cluster up using ctool. I tried couple of different ways but didn't seem to work. I'll look into more options for doing the same.

**Pull request merged**
